name: release
on:
  workflow_run:
    workflows:
      - tests
    branches: master
    types:
      - completed

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Initialize project
        run: |
          make init
      - name: Build package
        run: |
          make build
